# Python/Numpy/Pandas Primer

## Basic Data Structures and Data Types


In [2]:
#variables
var = 'blah' #strings can be accessed like a list
print(var[0:2])
var = 123
print(var % 5) #modulo
print(var / 5) #floating point/decimal division
print(var // 5) #keeps result the same data type as the inputs but truncates the result to be whole number still
var = 123.0
print(var//5)
print(var**2) #exponent
print(var*2)



#lists
lst = [] # initialization
lst = list()
lst = [1,2]
lst.append(1) #append adds element to the end of the list/array - rightmost element - very fast operation
lst.append("Sheesh") #you can store different data types in the same list -  '' and "" are the same for the most part
lst.extend(['I', "joined", 'CDS']) #you can extend a list with another list of elements - very slow operation
lst.pop() #remove last element - very fast operation
print("List contents: ", lst)
# List comprehension - try and see if you can understand what's happening here
l = [x for x in range(101) if x % 2 == 0] 
print(l)
lst #Jupyter notebooks print the last line of the cell automatically

bl
3
24.6
24
24.0
15129.0
246.0
List contents:  [1, 2, 1, 'Sheesh', 'I', 'joined']
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


[1, 2, 1, 'Sheesh', 'I', 'joined']

In [3]:
#Dictionaries
dic = {}
dic = dict()
dic = {1: 0, 'Jerry': "education", 'bro': None}
dic[1] = 2
print(dic)
print(dic.get('Jerry'))
print(dic['bro'])
print(dic.keys()) # you can access these like a list
print(dic.values())
dic.get('bob')#.get is None while dic['bob'] returns an error, None also only shows with print()

{1: 2, 'Jerry': 'education', 'bro': None}
education
None
dict_keys([1, 'Jerry', 'bro'])
dict_values([2, 'education', None])


In [4]:
#Sets and Tuples aren't as useful, here's a small rundown
#Sets
s = set() #no duplicates
s.add(3)
s.add(3)
s.add(4)
print(s) #you can't access it via subscripting

#Tuples
s = (1,2,3) #enforce same data type
#Not mutable/changeable


{3, 4}


## Python Programming

In [5]:
def function_call(parameter, second: str): #function calls
    for i in second:
        print(i)
    for j in range(len(second)):
        #print(second[j])
        print('this does the same thing')
        break #exits out of the most recent for loop
    for index, k in enumerate(second):
        print('this setup is the same as the first but index is also present and k is the valuee')
        break
    shihao = 'hype'
    if shihao == 'hype':
        print('brochocho')
    elif shihao != 'hype':
        print('yo')
    else:
        print('hi')
    while True:
        print('while loops')
        break
        
    return parameter

var = function_call(123, 'Onboarding is hype!')

#Object Oriented Programming
class Onboarding:
    def __init__(self, name):
        self.test = name
        self.dad = 'magd'

obj = Onboarding('shihao')
print(obj.test)

O
n
b
o
a
r
d
i
n
g
 
i
s
 
h
y
p
e
!
this does the same thing
this setup is the same as the first but index is also present and k is the valuee
brochocho
while loops
shihao


## Imports

In [6]:
import numpy as np #need this installed first, can shorten the name for function calls

## Numpy Tutorial

This activity is by no means a complete tutorial on NumPy but it should be enough for you to get started. For more information, please see NumPy's <a href="https://docs.scipy.org/doc/numpy/user/quickstart.html">official tutorial</a> and <a href='https://docs.scipy.org/doc/numpy/reference/index.html'>API</a>. 
<h2>Creating Vectors and Matrices</h2>

<p> NumPy's main object is a multidimensional array, in other words, a table of the same data type. Let's see an example on how to create an NumPy array:  </p>

In [7]:
X = np.array([[1,2,3], [4,5,6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In the cell above, we created a two dimensional table, a.k.a, a matrix of size $2 \times 3$. To create an array, what you need to do is to pass in a list of objects into the function [np.array()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html). Now that we have shown you how to create a matrix, you might have wondered how we can represent a vector in NumPy. There are three ways to represent a vector in NumPy. In the cell below we are using the function [.reshape()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) to specify the length of the 2-D array in each dimension.


In [8]:
v1=np.array([3,4,5])
print("This is a numpy vector:{}. It's shape is {}".format(v1, v1.shape))
v2=v1.reshape((3,1))
print("This is a column vector (matrix):\n{}. It's shape is {}".format(v2, v2.shape))
v3=v1.reshape((1,3))
print("This is a row vector (matrix):{}. It's shape is {}".format(v3,v3.shape))


This is a numpy vector:[3 4 5]. It's shape is (3,)
This is a column vector (matrix):
[[3]
 [4]
 [5]]. It's shape is (3, 1)
This is a row vector (matrix):[[3 4 5]]. It's shape is (1, 3)


<p><p>These three representation are usually not compatible. Some operations will still work, but not in the way we expect. </p> We will always prefer the vector notation. You can transform any (matrix) vector into a numpy vector with [.flatten()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html).</p>

In [9]:
#We add v1 and v2 but the output is not as expected
v4=v2+v1
print('The sum of a column vector and numpy vector:\n{}'.format(v4))
v5 = v2.flatten() + v1 
print('The expected result of summing two numpy vectors: {}'.format(v5))

The sum of a column vector and numpy vector:
[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]
The expected result of summing two numpy vectors: [ 6  8 10]


Numpy arrays, as objects, pass by reference.  This means that when you set return an array, you're returning a pointer (reference) to the real array in memory, and doing operations on the array will modify its values for every variable pointing to the array.  Because of this, numpy provides a [.copy()](https://numpy.org/doc/stable/reference/generated/numpy.copy.html) function, which will create a completely new array with the same values so that you can safely edit variables independently.


In [10]:
a = np.array([1,2,3])
b = a
c = a.copy()
print('Array a: {}'.format(a))
print('Array b (passed by reference): {}'.format(b))
print('Array c (passed by value): {}'.format(c))
a[0] = 5
print('Array a after editing a: {}'.format(a))
print('Array b after editing a: {}'.format(b))
print('Array c after editing a: {}'.format(c))

Array a: [1 2 3]
Array b (passed by reference): [1 2 3]
Array c (passed by value): [1 2 3]
Array a after editing a: [5 2 3]
Array b after editing a: [5 2 3]
Array c after editing a: [1 2 3]


### Axes

Numpy defines axes for arrays by giving them a number, so that functions can act along a certain dimension on the array. 

For a 1 dimensional array the axis is defined as <br>
$\left[\begin{array}{ccc}
axis0 → & 0 & 0 \\
\end{array}\right]$

For a 2 dimensional array the axis are defined as <br>
$\left[\begin{array}{ccc}
0 & axis 1 → & 0 \\
axis 0  & 0  & 0 \\
↓ & 0  & 0 \\
0 & 0  & 0 \\
\end{array}\right]$

The same pattern continues when more dimensions are added.

When you want to apply a function along a particular axis, you pass the axis number into the numpy function as an optional argument "axis=..." If you set axis=-1 it uses the last axis. For example, if there are three axis then axis=-1 is equivalent to axis=2. 

An example of using the axis argument with the sum function is below. This function sums up the matrix elements along the given axis. 

In [11]:
A = np.array([[1,-1],[1,-1],[1,-1]])
print('Original matrix: \n{}'.format(A))
print('Summed along axis = 0: \n{}'.format(np.sum(A, axis=0)))
print('Summed along axis = 1: \n{}'.format(np.sum(A, axis=1)))
print('Summed along axis = -1, which is the same as the last axis=1: \n{}'.format(np.sum(A, axis = -1)))

Original matrix: 
[[ 1 -1]
 [ 1 -1]
 [ 1 -1]]
Summed along axis = 0: 
[ 3 -3]
Summed along axis = 1: 
[0 0 0]
Summed along axis = -1, which is the same as the last axis=1: 
[0 0 0]


### Concatenation

Numpy arrays can also be concatenated in various ways.  This particular feature often requires practice to feel natural; however, the [concatenate](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) function can concatenate any number of arrays along any axis.

In [12]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])

print('First matrix: \n{}'.format(a))
print('Second matrix: \n{}'.format(b))
print('Concatenated matrices (first axis is default): \n{}'.format(np.concatenate((a, b))))
print('Concatenated along the second axis: \n{}'.format(np.concatenate((a, b), axis=-1)))

First matrix: 
[[1 2 3]
 [4 5 6]]
Second matrix: 
[[ 7  8  9]
 [10 11 12]]
Concatenated matrices (first axis is default): 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Concatenated along the second axis: 
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


<h3> Attributes of Numpy Arrays </h3>

Three important attributes of NumPy array are [.shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html), [.ndim](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ndim.html), and [.size](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.size.html): 

In [13]:
# the shape of an array
print("The shape of X: {}".format(X.shape))

# the dimension of an array
print("The dimension of X: {}".format(X.ndim))

#total number of elements of an array
print("The size of X: {}".format(X.size))

The shape of X: (2, 3)
The dimension of X: 2
The size of X: 6


<h3>Common Arrays</h3>

There are also functions for creating common matrices such as [eye()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html), [zeros()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html), and [arange()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html). Eye() creates an identity matrix, zero() creates a matrix of all zeros, and arange() creates a vector of equally spaced values.

In [14]:
print('Identity matrix of length 3:\n {}'.format(np.eye(3)))
print('Zero matrix of shape 2 by 3:\n {}'.format(np.zeros([2,3])))
print('Vector incrementing by 2 each element:\n {}'.format(np.arange(1,11,2)))

Identity matrix of length 3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Zero matrix of shape 2 by 3:
 [[0. 0. 0.]
 [0. 0. 0.]]
Vector incrementing by 2 each element:
 [1 3 5 7 9]


<h2>Matrix Operations</h2>
<p>In this section we will cover matrix functions that you will find useful in future projects. In many instances rather than writing functions from scratch there will be preexisting numpy functions which are faster and will save you time.</p> 

In [15]:
# Create some matrices
X = np.array([[1,2], [3,4]])
Y = np.array([[5,6], [7,8]])
A = np.array([[1,2,3,4], [7,8,9,10]])
B = np.array([[4,5,6,7], [1,2,3,4]])

To perform matrix multiplication use [np.dot()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) or the @ symbol. Using the traditional Python multiplication will multiply the values of the matrix element-wise.

In [16]:
print('X: \n{}'.format(X))
print('Y: \n{}'.format(Y))
print('Element-wise multiplication:\n{}'.format(X*Y))
print('Matrix multiplication:\n{}'.format(np.dot(X,Y)))
print('Alternative syntax for matrix multiplication:\n{}'.format(X @ Y))

X: 
[[1 2]
 [3 4]]
Y: 
[[5 6]
 [7 8]]
Element-wise multiplication:
[[ 5 12]
 [21 32]]
Matrix multiplication:
[[19 22]
 [43 50]]
Alternative syntax for matrix multiplication:
[[19 22]
 [43 50]]


To tranpose a matrix use [.transpose()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html). An alternative and more concise syntax is .T. 

In [17]:
print('B transposed:\n', B.transpose())
print('Alternative syntax for transpose:\n', B.T)

B transposed:
 [[4 1]
 [5 2]
 [6 3]
 [7 4]]
Alternative syntax for transpose:
 [[4 1]
 [5 2]
 [6 3]
 [7 4]]


### Exercise 1
<p>Use NumPy to calculate $AB^T-Y$. The output should be: $[[ 55,  24],
       [185,  82]]$</p>

In [ ]:
# CODE HERE

<h2>Indexing and Slicing</h2>
<p>NumPy's array can indexed and sliced, just like python's list. For single dimension array operations: </p>

In [18]:
x1 = np.arange(5)

print("x1: {}".format(x1))
print("Indexing a single element: {}".format(x1[3]))
print("Slicing: {}".format(x1[1:3]))  
print("Slicing last two numbers: {}".format(x1[-2:]))


x1: [0 1 2 3 4]
Indexing a single element: 3
Slicing: [1 2]
Slicing last two numbers: [3 4]


Another important feature with regards to slicing is that you can slice a numpy array using another numpy array.  It's worth playing around with this to see what's possible and what isn't!

In [19]:
y1 = np.array([30,40,50,20,10])
y1_slice = np.array([2,1,0])
print("y1: {}".format(y1))
print('Indexes to slice: {}'.format(y1_slice))
print('Returned values: {}'.format(y1[y1_slice]))
print('Argsort on y1: {}'.format(np.argsort(y1)))
print('y1 indexed by argsort: {}'.format(y1[np.argsort(y1)]))

y1: [30 40 50 20 10]
Indexes to slice: [2 1 0]
Returned values: [50 40 30]
Argsort on y1: [4 3 0 1 2]
y1 indexed by argsort: [10 20 30 40 50]


In [21]:
x2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("x2:\n{}".format(x2))
print("Full slice:\n{}".format(x2[::])) 
print("Indexing an element at the first row, third column: {}".format(x2[0,2]))
print("Slicing on both axes:\n{}".format(x2[1:,:2]))
print("Indexing by row:{}".format(x2[0])) # Selecting the first row 
print("Indexing by column: {}".format(x2[:,0])) # Selecting the first column

print("Iterating through each row in a matrix:")
for row in x2:
    print(row)

x2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Full slice:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Indexing an element at the first row, third column: 3
Slicing on both axes:
[[4 5]
 [7 8]]
Indexing by row:[1 2 3]
Indexing by column: [1 4 7]
Iterating through each row in a matrix:
[1 2 3]
[4 5 6]
[7 8 9]


# Pandas
Pandas is a primary data analysis library in Python. It offers a number of operations to aid in data exploration, cleaning and transformation, making it one of the most popular data science tools. To name a few examples of these operations, Pandas enables various methods to handle missing data and data pivoting, easy data sorting and description capabilities, fast generation of data plots, and Boolean indexing for fast image processing and other masking operations.


In [1]:
import pandas as pd

A Pandas `Series` is a one-dimensional `ndarray` (n-dimensional array). We can create a `series` simply by passing a list of values.


In [ ]:
first_series = pd.Series([10, 20, 30, 40])
print(first_series)
second_series = pd.Series(['lorem', 'ipsum'])
print(second_series)

### DataFrames
It's a two-dimensional tabular data structure in `Pandas` which helps in managing data in an orderly manner. The following are some key features of a  `Pandas DataFrame`:
<ul>
    <li>It has labelled axes
    <li>It's size is mutable
    <li>The columns may be of different datatypes
</ul>
An easy way to create a `DataFrame` is by passing a dictionary of objects.

In [3]:
df = pd.DataFrame({
                    'col1': pd.Series([10, 20, 30]),
                    'col2': 'hello world',
                    'col3': pd.Timestamp('20180101')
                   })
df

col1         col2       col3
0    10  hello world 2018-01-01
1    20  hello world 2018-01-01
2    30  hello world 2018-01-01

## Playing with DataFrames
`DataFrames` can also be created from pre-saved tables! A very common format for saving such tables is the .csv (which stands for comma-separated values) format. 

In [7]:
df=pd.read_csv('titanic.csv') #Titanic Dataset
df

PassengerId  Survived  Class  \
0              1         0      3   
1              2         1      1   
2              3         1      3   
3              4         1      1   
4              5         0      3   
..           ...       ...    ...   
886          887         0      2   
887          888         1      1   
888          889         0      3   
889          890         1      1   
890          891         0      3   

                                                  Name     Sex   Age  \
0                              Braund, Mr. Owen Harris    male  22.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2                               Heikkinen, Miss. Laina  female  26.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4                             Allen, Mr. William Henry    male  35.0   
..                                                 ...     ...   ...   
886                              Montvila, Rev. Juozas    male  27.0   
887                       Graham, Miss. Margaret Edith  female  19.0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
889                              Behr, Mr. Karl Howell    male  26.0   
890                                Dooley, Mr. Patrick    male  32.0   

               Ticket    Fare Cabin Port  
0           A/5 21171   7.250   NaN    S  
1            PC 17599     NaN   C85    C  
2    STON/O2. 3101282   7.925   NaN    S  
3              113803  53.100  C123    S  
4              373450   8.050   NaN    S  
..                ...     ...   ...  ...  
886            211536  13.000   NaN    S  
887            112053  30.000   B42    S  
888        W./C. 6607  23.450   NaN    S  
889            111369     NaN  C148    C  
890            370376   7.750   NaN    Q  

[891 rows x 10 columns]

In [8]:
# Check the columns in your dataframe
df.columns

Index(['PassengerId', 'Survived', 'Class', 'Name', 'Sex', 'Age', 'Ticket',
       'Fare', 'Cabin', 'Port'],
      dtype='object')

In [9]:
df.head(3) #df.tail() to see last few rows

PassengerId  Survived  Class  \
0            1         0      3   
1            2         1      1   
2            3         1      3   

                                                Name     Sex   Age  \
0                            Braund, Mr. Owen Harris    male  22.0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2                             Heikkinen, Miss. Laina  female  26.0   

             Ticket   Fare Cabin Port  
0         A/5 21171  7.250   NaN    S  
1          PC 17599    NaN   C85    C  
2  STON/O2. 3101282  7.925   NaN    S

In [10]:
df['Age'].tail(5)#To get a specific column

886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, dtype: float64

In [11]:
# Filtering
FareAbove20_OlderThan40=df.loc[(df['Fare']>20) & (df['Age']>40)]
FareAbove20_OlderThan40.head(10)

PassengerId  Survived  Class                                      Name  \
6              7         0      1                   McCarthy, Mr. Timothy J   
11            12         1      1                  Bonnell, Miss. Elizabeth   
35            36         0      1            Holverson, Mr. Alexander Oskar   
52            53         1      1  Harper, Mrs. Henry Sleeper (Myna Haxtun)   
54            55         0      1            Ostby, Mr. Engelhart Cornelius   
62            63         0      1               Harris, Mr. Henry Birkhardt   
92            93         0      1               Chaffee, Mr. Herbert Fuller   
96            97         0      1                 Goldschmidt, Mr. George B   
110          111         0      1            Porter, Mr. Walter Chamberlain   
124          125         0      1               White, Mr. Percival Wayland   

        Sex   Age       Ticket     Fare Cabin Port  
6      male  54.0        17463  51.8625   E46    S  
11   female  58.0       113783  26.5500  C103    S  
35     male  42.0       113789  52.0000   NaN    S  
52   female  49.0     PC 17572  76.7292   D33    C  
54     male  65.0       113509  61.9792   B30    C  
62     male  45.0        36973  83.4750   C83    S  
92     male  46.0  W.E.P. 5734  61.1750   E31    S  
96     male  71.0     PC 17754  34.6542    A5    C  
110    male  47.0       110465  52.0000  C110    S  
124    male  54.0        35281  77.2875   D26    S

`.loc` is a useful function, but is often confused with `.iloc`. Check out this <a href="https://stackoverflow.com/questions/31593201/how-are-iloc-ix-and-loc-different">Stack Overflow Post</a> to clarify the concept.

#### Concatenating Dataframes

In [13]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']})

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']})
pd.concat([df1,df2])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

<b>Summary Statistics</b>
We can check the statistics for individual columns by referring to the said column.

In [15]:
print(df['Fare'].mean())
print(df['Fare'].median())
df.describe()

31.164612066752248
14.4


PassengerId    Survived       Class         Age        Fare
count   891.000000  891.000000  891.000000  714.000000  779.000000
mean    446.000000    0.383838    2.308642   29.699118   31.164612
std     257.353842    0.486592    0.836071   14.526497   47.741674
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    7.895800
50%     446.000000    0.000000    3.000000   28.000000   14.400000
75%     668.500000    1.000000    3.000000   38.000000   30.035400
max     891.000000    1.000000    3.000000   80.000000  512.329200

## Data Imputation


In [16]:
df.head(4)

PassengerId  Survived  Class  \
0            1         0      3   
1            2         1      1   
2            3         1      3   
3            4         1      1   

                                                Name     Sex   Age  \
0                            Braund, Mr. Owen Harris    male  22.0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2                             Heikkinen, Miss. Laina  female  26.0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   

             Ticket    Fare Cabin Port  
0         A/5 21171   7.250   NaN    S  
1          PC 17599     NaN   C85    C  
2  STON/O2. 3101282   7.925   NaN    S  
3            113803  53.100  C123    S

In [18]:
df['Cabin']=df['Cabin'].fillna('Top Deck')
df.head(3)

PassengerId  Survived  Class  \
0            1         0      3   
1            2         1      1   
2            3         1      3   

                                                Name     Sex   Age  \
0                            Braund, Mr. Owen Harris    male  22.0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2                             Heikkinen, Miss. Laina  female  26.0   

             Ticket   Fare     Cabin Port  
0         A/5 21171  7.250  Top Deck    S  
1          PC 17599    NaN       C85    C  
2  STON/O2. 3101282  7.925  Top Deck    S

In [19]:
#Dummy Encoding
df['male']=0
df['female']=0
for x in range(0,len(df)):
    if df['Sex'][x]=='male':
        df['male'][x]=1
    else:
        df['female'][x]=1
df

<ipython-input-19-c675a5329a85>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['male'][x]=1
<ipython-input-19-c675a5329a85>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['female'][x]=1


PassengerId  Survived  Class  \
0              1         0      3   
1              2         1      1   
2              3         1      3   
3              4         1      1   
4              5         0      3   
..           ...       ...    ...   
886          887         0      2   
887          888         1      1   
888          889         0      3   
889          890         1      1   
890          891         0      3   

                                                  Name     Sex   Age  \
0                              Braund, Mr. Owen Harris    male  22.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2                               Heikkinen, Miss. Laina  female  26.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4                             Allen, Mr. William Henry    male  35.0   
..                                                 ...     ...   ...   
886                              Montvila, Rev. Juozas    male  27.0   
887                       Graham, Miss. Margaret Edith  female  19.0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
889                              Behr, Mr. Karl Howell    male  26.0   
890                                Dooley, Mr. Patrick    male  32.0   

               Ticket    Fare     Cabin Port  male  female  
0           A/5 21171   7.250  Top Deck    S     1       0  
1            PC 17599     NaN       C85    C     0       1  
2    STON/O2. 3101282   7.925  Top Deck    S     0       1  
3              113803  53.100      C123    S     0       1  
4              373450   8.050  Top Deck    S     1       0  
..                ...     ...       ...  ...   ...     ...  
886            211536  13.000  Top Deck    S     1       0  
887            112053  30.000       B42    S     0       1  
888        W./C. 6607  23.450  Top Deck    S     0       1  
889            111369     NaN      C148    C     1       0  
890            370376   7.750  Top Deck    Q     1       0  

[891 rows x 12 columns]

### Parting Fun Facts:

If you really like the resulting data frame you produced, and want to download it into a file to share with all your friends and family, you can do that! `to_csv()` or `to_excel()` allows you to save the dataframe locally.

